// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNr-qasil1FGhoVi7o9Fn_-SZ8h7b9zUM',
    appId: '1:815551150083:web:530404f70a788910317636',
    messagingSenderId: '815551150083',
    projectId: 'flutter-payment-stripe-demo',
    authDomain: 'flutter-payment-stripe-demo.firebaseapp.com',
    storageBucket: 'flutter-payment-stripe-demo.appspot.com',
    measurementId: 'G-YD4Y9ZKT4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9eu--FSbsVt_5srdi25iv8LVQ6Q78MX0',
    appId: '1:815551150083:android:1dc20148443620ea317636',
    messagingSenderId: '815551150083',
    projectId: 'flutter-payment-stripe-demo',
    storageBucket: 'flutter-payment-stripe-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ2pYM-GjwTj8LICkV0PtEMFVGTO35gh4',
    appId: '1:815551150083:ios:49f3590f1dd30d63317636',
    messagingSenderId: '815551150083',
    projectId: 'flutter-payment-stripe-demo',
    storageBucket: 'flutter-payment-stripe-demo.appspot.com',
    iosClientId: '815551150083-b0jp5e16g21jvvtvvkli112qni5c7jkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.webNavUseFrankFiireb',
  );
}
